-- ============================================================================
-- 010_nanov3_registry.sql
-- ----------------------------------------------------------------------------
-- Registers every NanoV3 parameter in nano_registry.
--
-- The Commands tab validates each `set` against nano_registry and refuses
-- PIDs it doesn't know, and the Config tab lists only registry rows. NanoV3
-- kept the Gen 2 ids for the parameters it shares but added new ones — the
-- analog-box I/O polarity group (P-50xx), the PT100 temperature group
-- (P-51xx), the measured status flags (P-4110..P-4122), OBD2 values
-- (P-4115..P-4117), DAC calibration (P-809/P-810) and others. Until they are
-- registered none of them can be set from the web.
--
-- GENERATED from NanoV3 components/config_manager/config_table.c at commit
-- 4338eb5 — all 91 parameters, so the registry cannot drift from what
-- the firmware accepts. Regenerate with tools/gen_registry_sql.py rather than
-- editing rows by hand.
--
-- ON CONFLICT (pid) DO NOTHING: rows already present (the Gen 2 set) are left
-- exactly as they are, so nothing changes for Gen 2 units. The three level
-- PIDs are the one place the generations disagree (Gen 2 "Level Low" vs
-- NanoV3 "water present"); the live/history screens handle that per frame
-- (lib/nano-pids.ts), so the registry keeps the Gen 2 wording.
--
-- band / category are copied from an existing row of the same group where the
-- group already exists in the registry; the groups new to NanoV3 (30 I/O,
-- 31 temperature, 32 adaptive RCS, 33 heating jacket) use the firmware group
-- number and name.
-- ============================================================================

INSERT INTO nano_registry
  (pid, pid_num, band, category, name, description, data_type, units,
   valid_range, enum_values, default_value, access, settable_via,
   sms_eligible, auth_req, presence, source, proposed, notes)
VALUES
  ('P-104', 104, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-104'), 1), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-104'), 'Identity'), 'Firmware Version', 'Set by firmware at boot from the build version.', 'string', NULL,
   NULL, NULL, NULL, 'RO', '{}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-107', 107, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-104'), 1), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-104'), 'Identity'), 'SIM ICCID', 'Captured from the SIM on first attach.', 'string', NULL,
   NULL, NULL, NULL, 'RO', '{}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-108', 108, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-104'), 1), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-104'), 'Identity'), 'Modem IMEI', 'Captured from the modem; becomes the MQTT identity.', 'string', NULL,
   NULL, NULL, NULL, 'RO', '{}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-401', 401, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-401'), 4), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-401'), 'Cellular'), 'APN', 'Carrier APN. Modem stays off until this is set.', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-501', 501, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Broker Host', 'GreenVision broker hostname/IP. Required.', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-502', 502, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Broker Port', 'TCP port. Plain TCP only.', 'uint16', NULL,
   '1..65535', NULL, '1883', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-503', 503, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Client ID', 'Identity override; used only if P-108 is empty.', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-504', 504, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Username', 'Broker login. Empty = anonymous connect.', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-505', 505, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Password', 'Broker password. Never read back in clear (echoes as ***).', 'string', NULL,
   NULL, NULL, NULL, 'WO', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-506', 506, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Keepalive', 'Keep-alive seconds.', 'uint16', 's',
   '10..600', NULL, '60', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-509', 509, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT Topic Prefix', 'Prefix before <id>/tel, /cmd, /status.', 'string', NULL,
   NULL, NULL, 'sgt/nano/', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-510', 510, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-501'), 5), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-501'), 'MQTT'), 'MQTT QoS Level', 'QoS for publishes. QoS 1 = broker-confirmed.', 'enum', NULL,
   NULL, '{"0","1","2"}'::text[], '1', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-602', 602, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-602'), 6), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-602'), 'Telemetry Cadence'), 'Publish Interval (engine on)', 'Seconds between frames while the engine-run input is active.', 'uint16', 's',
   '5..3600', NULL, '60', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-603', 603, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-602'), 6), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-602'), 'Telemetry Cadence'), 'Publish Interval (engine off)', 'Seconds between frames while the engine is off.', 'uint16', 's',
   '5..3600', NULL, '300', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-604', 604, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-602'), 6), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-602'), 'Telemetry Cadence'), 'GPS Report Interval', 'Seconds between GNSS polls.', 'uint16', 's',
   '5..3600', NULL, '300', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-609', 609, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-602'), 6), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-602'), 'Telemetry Cadence'), 'Report on Input Change', 'Send an immediate frame when any digital input changes.', 'bool', NULL,
   NULL, NULL, 'true', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-802', 802, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-802'), 8), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-802'), 'Remote Current Setting'), 'RCS Current Setpoint', 'Requested electrolyser current, amps. Drives the MCP4725 DAC. Published in telemetry.', 'float', 'A',
   '0..30', NULL, '8', 'RW', '{"Cloud","SMS","CLI"}'::text[],
   true, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-803', 803, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-802'), 8), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-802'), 'Remote Current Setting'), 'RCS Max Current Limit', 'Ceiling applied to P-802.', 'float', 'A',
   '0..30', NULL, '20', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-809', 809, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-802'), 8), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-802'), 'Remote Current Setting'), 'DAC Full-Scale Cal (code @ P-803)', 'DAC code (0-4095) measured to give P-803 amps.', 'float', NULL,
   '0..4095', NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-810', 810, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-802'), 8), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-802'), 'Remote Current Setting'), 'DAC Zero Cal (code @ 0 A)', 'DAC code measured to give 0 A. Unset = nominal 0.5 V + 100 mV/A on 3.3 V ref.', 'float', NULL,
   '0..4095', NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-3026', 3026, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-3026'), 10), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-3026'), 'Battery'), 'Battery Sense Calibration', 'Multiplier on the nominal 10:1 divider (e.g. 1.02). Unset = 1.0.', 'float', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1101', 1101, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1101'), 13), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1101'), 'Remote Stop/Start'), 'Remote Stop/Start', 'Run releases, Stop asserts the remote-stop output (GPIO43). Persisted across reboot.', 'enum', NULL,
   NULL, '{"Run","Stop"}'::text[], 'Run', 'RW', '{"Cloud","SMS","CLI"}'::text[],
   true, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1301', 1301, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1301'), 17), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1301'), 'SMS'), 'Admin Phone 1', 'Number allowed to send SMS commands (E.164 or national form).', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1302', 1302, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1301'), 17), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1301'), 'SMS'), 'Admin Phone 2', 'Second admin number.', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1303', 1303, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1301'), 17), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1301'), 'SMS'), 'SMS Commands Enable', 'Master enable for SMS commands.', 'bool', NULL,
   NULL, NULL, 'true', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1306', 1306, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1301'), 17), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1301'), 'SMS'), 'SMS Reply Enable', 'Reply to each SMS command.', 'bool', NULL,
   NULL, NULL, 'true', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1308', 1308, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1301'), 17), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1301'), 'SMS'), 'Device SIM Number', 'Record of the device''s own number (informational).', 'string', NULL,
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1501', 1501, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1501'), 19), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1501'), 'Local Flash Log'), 'Flash Logging Enable', 'Write telemetry frames to the 2 MB storage partition.', 'bool', NULL,
   NULL, NULL, 'true', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-1502', 1502, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-1501'), 19), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-1501'), 'Local Flash Log'), 'Flash Log Interval', 'Minimum seconds between stored frames.', 'uint16', 's',
   '5..3600', NULL, '60', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4061', 4061, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4075'), 24), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4075'), 'Electrolyser Current Sense'), 'Current Sense Full-Scale', 'Clamp, amps.', 'float', NULL,
   '1..200', NULL, '30', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4062', 4062, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4075'), 24), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4075'), 'Electrolyser Current Sense'), 'Current Sense Gain Cal', 'Millivolts per amp at the ADC pin. Unset = 100.', 'float', 'mV',
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4063', 4063, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4075'), 24), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4075'), 'Electrolyser Current Sense'), 'Current Sense Zero Offset', 'Millivolts at the ADC pin at 0 A. Unset = 500.', 'float', 'mV',
   NULL, NULL, NULL, 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4075', 4075, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4075'), 24), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4075'), 'Electrolyser Current Sense'), 'Measured Cell Current', 'Amps, from ADC1_CH0 (GPIO1).', 'float', 'A',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4093', 4093, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Supply Voltage', 'Battery volts, from ADC1_CH1 (GPIO2).', 'float', 'V',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4096', 4096, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Level Sensor - Main (water present)', 'true = water present (GPIO40).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4097', 4097, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Level Sensor - Bubbler (water present)', 'true = water present (GPIO41).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4098', 4098, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Level Sensor - Electrolyte (water present)', 'true = water present (GPIO42).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4100', 4100, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Active Bearer', 'Current network bearer.', 'enum', NULL,
   NULL, '{"None","Cell"}'::text[], 'None', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4101', 4101, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Signal RSSI', 'dBm.', 'uint32', 'dBm',
   '-113..-51', NULL, '0', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4104', 4104, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Engine RPM', 'From CAN (J1939 or OBD2).', 'float', 'rpm',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4105', 4105, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Engine Load', '%, from CAN.', 'float', '%',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4106', 4106, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Fuel Rate', 'L/h, from CAN.', 'float', 'L/h',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4107', 4107, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Total Fuel Used', 'L, J1939 only.', 'float', 'L',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4108', 4108, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Engine Hours', 'h, J1939 only.', 'float', 'h',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4110', 4110, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Pump 1 Status', 'true = running (GPIO4).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4111', 4111, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Pump 2 Status', 'true = running (GPIO5).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4112', 4112, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Solenoid Valve Status', 'true = open (GPIO6).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4113', 4113, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Engine Running', 'Alternator input (GPIO44). Selects P-602 / P-603 cadence.', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4114', 4114, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Remote Stop Output Asserted', 'true = stop line (GPIO43) driven.', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4115', 4115, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Vehicle Speed', 'km/h, OBD2 only.', 'float', 'km/h',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4116', 4116, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Coolant Temp', '°C, OBD2 only.', 'float', '°C',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4117', 4117, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Fuel Level', '%, OBD2 only.', 'float', '%',
   NULL, NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4200', 4200, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4200'), 27), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4200'), 'CAN'), 'CAN Enable', 'Start the CAN controller. Off by default.', 'bool', NULL,
   NULL, NULL, 'false', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4201', 4201, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4200'), 27), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4200'), 'CAN'), 'CAN Bit Rate', 'kbit/s. J1939 is 250; OBD2 usually 500.', 'enum', NULL,
   NULL, '{"125","250","500","1000"}'::text[], '250', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4203', 4203, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4200'), 27), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4200'), 'CAN'), 'CAN Signal Timeout', 'ms after which a CAN signal is stale and omitted from telemetry.', 'uint16', 'ms',
   '250..60000', NULL, '3000', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4204', 4204, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4200'), 27), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4200'), 'CAN'), 'CAN Protocol', 'J1939 = listen-only; OBD2 = polled mode-01 requests.', 'enum', NULL,
   NULL, '{"J1939","OBD2"}'::text[], 'J1939', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4206', 4206, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4200'), 27), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4200'), 'CAN'), 'OBD2 Poll Interval', 'ms between OBD2 PID requests.', 'uint16', 'ms',
   '100..5000', NULL, '500', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4300', 4300, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4300'), 28), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4300'), 'Outage Buffer'), 'Buffer Enable', 'Keep frames in PSRAM while offline; drain oldest-first on reconnect.', 'bool', NULL,
   NULL, NULL, 'true', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4302', 4302, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4300'), 28), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4300'), 'Outage Buffer'), 'Buffer Capacity', 'Frames held.', 'uint32', 'frames',
   '64..100000', NULL, '2048', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5001', 5001, 30, 'Analog-Box I/O Interface', 'Level Inputs Active Level', 'Pin level meaning "water present" on GPIO40/41/42.', 'enum', NULL,
   NULL, '{"High","Low"}'::text[], 'High', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5002', 5002, 30, 'Analog-Box I/O Interface', 'Pump/Valve Inputs Active Level', 'Pin level meaning "running / open" on GPIO4/5/6.', 'enum', NULL,
   NULL, '{"High","Low"}'::text[], 'High', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5003', 5003, 30, 'Analog-Box I/O Interface', 'Engine Run Input Active Level', 'Pin level meaning "engine running" on GPIO44.', 'enum', NULL,
   NULL, '{"High","Low"}'::text[], 'High', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5010', 5010, 30, 'Analog-Box I/O Interface', 'Remote Stop Output Active Level', 'Pin level the analog box reads as "stop" on GPIO43.', 'enum', NULL,
   NULL, '{"High","Low"}'::text[], 'High', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5101', 5101, 31, 'Temperature Sensor', 'Temperature Sensor Enable', 'Enable PT100 + MAX31865 sampling (1 Hz) and thermal shutdown.', 'bool', NULL,
   NULL, NULL, 'false', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5102', 5102, 31, 'Temperature Sensor', 'Temperature High Threshold', '°C; at or above this triggers shutdown.', 'float', '°C',
   '-40..125', NULL, '90', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5103', 5103, 31, 'Temperature Sensor', 'Temperature Low Threshold', '°C; at or below this triggers shutdown (freeze protection).', 'float', '°C',
   '-40..125', NULL, '0', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5104', 5104, 31, 'Temperature Sensor', 'Temperature Shutdown Mode', 'Which limits trigger a stop.', 'enum', NULL,
   NULL, '{"High Only","Low Only","Both"}'::text[], 'Both', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5105', 5105, 31, 'Temperature Sensor', 'Temperature Recovery Delay', 'Seconds to wait after temperature returns to range before auto-restart (P-1101 = Run).', 'uint16', 's',
   '5..300', NULL, '60', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5106', 5106, 31, 'Temperature Sensor', 'Temperature Resume Band', 'Temperature must come back inside the limits by this many °C before the lockout clears (hysteresis).', 'float', '°C',
   '0..20', NULL, '3', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5107', 5107, 31, 'Temperature Sensor', 'RTD Wires', 'PT100 wiring: 2, 3 or 4-wire (MAX31865 configuration).', 'enum', NULL,
   NULL, '{"2","3","4"}'::text[], '3', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5108', 5108, 31, 'Temperature Sensor', 'RTD Mains Filter', 'MAX31865 mains-rejection filter, matches local mains frequency.', 'enum', NULL,
   NULL, '{"50","60"}'::text[], '50', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5109', 5109, 31, 'Temperature Sensor', 'RTD Reference Resistor', 'MAX31865 reference resistor in ohms (430 on the common breakout).', 'float', NULL,
   '100..5000', NULL, '430', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4118', 4118, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Measured Electrolyser Temperature', '°C from the PT100 via MAX31865.', 'float', '°C',
   '-40..125', NULL, '0', 'RO', '{}'::text[],
   false, false, 'conditional', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4119', 4119, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Temperature Sensor Present', 'true = MAX31865 responding and RTD OK.', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4120', 4120, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Thermal Lockout Active', 'Thermal guard is holding the remote-stop line after an out-of-range temperature; clears after P-5105.', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-5110', 5110, 33, 'Heating Jacket', 'Heat Jacket Enable', 'Enable the heating jacket for sub-zero sites (needs PCF8575 on the I2C bus).', 'bool', NULL,
   NULL, NULL, 'false', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5111', 5111, 33, 'Heating Jacket', 'Heat Jacket On Temperature', 'Jacket switches on at or below this temperature.', 'float', '°C',
   '-40..125', NULL, '3', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5112', 5112, 33, 'Heating Jacket', 'Heat Jacket Off Temperature', 'Jacket switches off at or above this temperature (hysteresis).', 'float', '°C',
   '-40..125', NULL, '8', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5113', 5113, 33, 'Heating Jacket', 'Heat Jacket Expander Line', 'PCF8575 line (P0..P15) driving the jacket relay.', 'uint16', NULL,
   '0..15', NULL, '9', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5114', 5114, 33, 'Heating Jacket', 'Heat Jacket Output Active Level', 'Expander output level that energises the jacket.', 'enum', NULL,
   NULL, '{"High","Low"}'::text[], 'Low', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-4121', 4121, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Heat Jacket On', 'Heating jacket output energised (via PCF8575 expander).', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-4122', 4122, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Heat Jacket Expander Fault', 'PCF8575 expander not responding or read-back mismatch; sent only when true.', 'bool', NULL,
   NULL, NULL, 'false', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-5200', 5200, 32, 'Adaptive RCS', 'RCS Engine Type', 'Engine class for adaptive RCS: Vehicle (RPM zones) or DG (load zones).', 'enum', NULL,
   NULL, '{"Vehicle","DG"}'::text[], 'Vehicle', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5201', 5201, 32, 'Adaptive RCS', 'RCS Control Mode', 'Manual = P-802 is used as set; Auto = firmware picks P-5206..P-5209 by zone.', 'enum', NULL,
   NULL, '{"Manual","Auto"}'::text[], 'Manual', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5202', 5202, 32, 'Adaptive RCS', 'RCS Fallback Current', 'Current used in Auto mode when CAN gives no valid RPM/load.', 'float', 'A',
   '0..30', NULL, '8', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5206', 5206, 32, 'Adaptive RCS', 'RCS Zone 1 Current', 'Auto-mode current for zone 1 (lowest RPM / load band).', 'float', 'A',
   '0..30', NULL, '8', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5207', 5207, 32, 'Adaptive RCS', 'RCS Zone 2 Current', 'Auto-mode current for zone 2.', 'float', 'A',
   '0..30', NULL, '8', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5208', 5208, 32, 'Adaptive RCS', 'RCS Zone 3 Current', 'Auto-mode current for zone 3.', 'float', 'A',
   '0..30', NULL, '8', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5209', 5209, 32, 'Adaptive RCS', 'RCS Zone 4 Current', 'Auto-mode current for zone 4 (highest band).', 'float', 'A',
   '0..30', NULL, '8', 'RW', '{"Cloud","CLI"}'::text[],
   false, false, NULL, 'NanoV3 config_table.c', false, 'persist'),
  ('P-5250', 5250, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'Active RCS Zone', 'Zone currently selected by adaptive RCS (0 = inactive). Published while Auto.', 'uint16', NULL,
   '0..4', NULL, '0', 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only'),
  ('P-5251', 5251, COALESCE((SELECT band FROM nano_registry WHERE pid = 'P-4093'), 26), COALESCE((SELECT category FROM nano_registry WHERE pid = 'P-4093'), 'Measured Values'), 'RCS Zone Reason', 'Why that zone was chosen (e.g. rpm, load, fallback). Published while Auto.', 'string', NULL,
   NULL, NULL, NULL, 'RO', '{}'::text[],
   false, false, 'always', 'NanoV3 config_table.c', false, 'runtime only')
ON CONFLICT (pid) DO NOTHING;


DO $$
DECLARE missing integer;
BEGIN
  SELECT count(*) INTO missing FROM (VALUES ('P-104'), ('P-107'), ('P-108'), ('P-401'), ('P-501'), ('P-502'), ('P-503'), ('P-504'), ('P-505'), ('P-506'), ('P-509'), ('P-510'), ('P-602'), ('P-603'), ('P-604'), ('P-609'), ('P-802'), ('P-803'), ('P-809'), ('P-810'), ('P-3026'), ('P-1101'), ('P-1301'), ('P-1302'), ('P-1303'), ('P-1306'), ('P-1308'), ('P-1501'), ('P-1502'), ('P-4061'), ('P-4062'), ('P-4063'), ('P-4075'), ('P-4093'), ('P-4096'), ('P-4097'), ('P-4098'), ('P-4100'), ('P-4101'), ('P-4104'), ('P-4105'), ('P-4106'), ('P-4107'), ('P-4108'), ('P-4110'), ('P-4111'), ('P-4112'), ('P-4113'), ('P-4114'), ('P-4115'), ('P-4116'), ('P-4117'), ('P-4200'), ('P-4201'), ('P-4203'), ('P-4204'), ('P-4206'), ('P-4300'), ('P-4302'), ('P-5001'), ('P-5002'), ('P-5003'), ('P-5010'), ('P-5101'), ('P-5102'), ('P-5103'), ('P-5104'), ('P-5105'), ('P-5106'), ('P-5107'), ('P-5108'), ('P-5109'), ('P-4118'), ('P-4119'), ('P-4120'), ('P-5110'), ('P-5111'), ('P-5112'), ('P-5113'), ('P-5114'), ('P-4121'), ('P-4122'), ('P-5200'), ('P-5201'), ('P-5202'), ('P-5206'), ('P-5207'), ('P-5208'), ('P-5209'), ('P-5250'), ('P-5251')) v(pid)
   WHERE NOT EXISTS (SELECT 1 FROM nano_registry r WHERE r.pid = v.pid);
  IF missing > 0 THEN
    RAISE EXCEPTION 'nano_registry still missing % NanoV3 parameter(s)', missing;
  END IF;
  RAISE NOTICE 'nano_registry: all 91 NanoV3 parameters present.';
END $$;
